openapi: "3.0.1"
info:
  title: Hello API
  version: "1.0"
  description: A simple Rest API written using OpenAPI Specification

paths:
  /hello:
    get:
      summary: Simple Lambda integration
      description: Simple Lambda integration with a function previously created.
      parameters:
        - name: name
          in: query
          required: true
          description: The person's name
          schema:
            type: string
        - name: age
          in: query
          required: true
          description: The person's age
          schema:
            type: integer
      responses:
        200:
          description: A normal output name / old
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name:
                    type: string
                  Old:
                    type: boolean
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:123123123123:function:HelloLambda/invocations
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "Name": "$input.params('name')",
              "Age": $input.params('age')
            }
        responses:
          "default":
            statusCode: 200
            responseTemplates:
              application/json: |
                #set ($root=$input.path('$')) 
                {
                  "Message": "Dear $root.Name, you are#if(!$root.Old) not#end old."
                }
